apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskboard
  template:
    metadata:
      labels:
        app: taskboard
    spec:
      containers:
      - name: taskboard
        image: dlg8/taskboardapp:latest
        ports:
        - containerPort: 80
