apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskboard-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskboard-app
  template:
    metadata:
      labels:
        app: taskboard-app
    spec:
      containers:
        - name: taskboard-container
          image: dlg8/taskboardapp:latest
          ports:
            - containerPort: 80
          env:
            - name: DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: taskboard-secret
                  key: DefaultConnection
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-secret
                  key: SA_PASSWORD
