name: Deploy to AKS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t dlg8/taskboardapp:latest -f TaskBoard.WebApp/Dockerfile .

    - name: Push Docker image
      run: docker push dlg8/taskboardapp:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: kubernetesrg
        cluster-name: dlgCluster

    - name: Create secret for SQL Server password
      run: |
        kubectl create secret generic sql-secret \
          --from-literal=SA_PASSWORD=${{ secrets.SQL_SA_PASSWORD }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Create secret for app connection string
      run: |
        kubectl create secret generic taskboard-secret \
          --from-literal=DefaultConnection="${{ secrets.DEFAULT_CONNECTION }}" \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/Sql-deployment.yaml
        kubectl apply -f k8s/Sql-service.yaml
        kubectl apply -f k8s/Deployment.yaml
        kubectl apply -f k8s/Service.yaml
